#!/bin/bash

die() { echo "$*" 1>&2 ; exit 1; }

rm -rf tstdata || die
mkdir -p tstdata || die
cd tstdata || die
head -30000 /dev/urandom > data.bin || die
../ssssw split 7 5 data.bin || die
../ssssw combine data.bin.share* || die
diff data.bin data-*.bin || die
echo
echo "test passed"
